version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    expose:
      - "6101"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.18
    command:
      - "postgres"
      - "-c"
      - "port=6101"
  app:
    build:
      context: .
    container_name: auth_service
    env_file:
      - .env
    ports:
      - "6100:6100"
    depends_on:
      - db_auth