version: '3.5'
# 6100 - auth service
#6101 - auth_db
services:
  db_auth:
    container_name: db_auth
    ports:
      - "6101:6101"
    expose:
      - "6101"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
    image: postgres:alpine3.18
    command:
      - "postgres"
      - "-c"
      - "port=6101"
  app:
    build:
      context: .
    container_name: auth_service
    ports:
      - "6100:6100"
    depends_on:
      - db_auth